### ISSUE TITLE
Scribus plugins fail to load

### ISSUE THREAD

**Issue by mneumann** [DragonFlyBSD/DeltaPorts#815] opened 2017-12-08 17:40 UTC
When I start scribus-1.4.6_9, I get the following output on console:

```
% scribus 
Cannot find plugin: /usr/local/lib/scribus/plugins//libwmfimplugin.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libtransformeffect.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsvgimplugin.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsvgexplugin.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsubdivide.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscriptplugin.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribusshortwords.so: Undefined symbol "_ZN12SpecialChars7NBSPACEE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribusexportpixmap.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus13format.so: Undefined symbol "_ZTV11MissingFont"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus134format.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus12format.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsaveastemplateplugin.so: Undefined symbol "ScCore"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathstroker.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathfinder.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathcut.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathconnect.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathalongpath.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//liboodrawimp.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libmeshdistortion.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//liblenseffects.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportxfig.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportps.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportpct.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportcvg.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportai.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libhunspellplugin.so: Undefined symbol "_ZTI11StoryEditor"
Cannot find plugin: /usr/local/lib/scribus/plugins//libfontpreview.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libcolorwheel.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libbarcodegenerator.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libbarcodegenerator.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libcolorwheel.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libfontpreview.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libhunspellplugin.so: Undefined symbol "_ZTI11StoryEditor"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportai.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportcvg.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportpct.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportps.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libimportxfig.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//liblenseffects.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libmeshdistortion.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//liboodrawimp.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathalongpath.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathconnect.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathcut.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathfinder.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libpathstroker.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsaveastemplateplugin.so: Undefined symbol "ScCore"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus12format.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus134format.so: Undefined symbol "_ZTV5Style"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribus13format.so: Undefined symbol "_ZTV11MissingFont"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribusexportpixmap.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscribusshortwords.so: Undefined symbol "_ZN12SpecialChars7NBSPACEE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libscriptplugin.so: Undefined symbol "_ZN13CommonStrings4NoneE"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsubdivide.so: Undefined symbol "_ZTI13UpdateMemento"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsvgexplugin.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libsvgimplugin.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libtransformeffect.so: Undefined symbol "_ZTI8ScPlugin"
Cannot find plugin: /usr/local/lib/scribus/plugins//libwmfimplugin.so: Undefined symbol "_ZN13CommonStrings4NoneE"
No File Loader Plugins Found
No File Loader Plugins Found
```

I cannot load most templates, probably because they depend on some plugins.

**Comment by zrj-rimwis** [comment] 2020-01-30 13:39
The print/scribus reached EOL and was removed from ports. I cannot reproduce the issue with print/scribus-devel (no plugin loading errors), so closing.

**Closed by zrj-rimwis** 2020-01-30 13:39 UTC

**Comment by mneumann** [comment] 2020-02-02 12:42
@zrj-rimwis I just tried out scribus-devel and it works! thanks!
